# Generated by Django 5.1.6 on 2025-02-22 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='profile_name',
        ),
    ]
