# Generated by Django 5.1.6 on 2025-02-23 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_interaction_match'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='id',
            new_name='user_id',
        ),
    ]
