# Generated by Django 5.1.6 on 2025-02-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_userprofile_is_admin_userprofile_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='goodreads_score',
            field=models.FloatField(null=True),
        ),
    ]
